# Generated by Django 5.1 on 2024-09-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_models", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="vendor_id",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
