# Generated by Django 5.1 on 2024-09-22 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_models", "0002_alter_category_vendor_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sub_category",
            field=models.ForeignKey(
                default=27,
                on_delete=django.db.models.deletion.CASCADE,
                to="data_models.subcategory",
            ),
            preserve_default=False,
        ),
    ]
