# Generated by Django 5.1 on 2024-09-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_models", "0003_product_sub_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ManyToManyField(to="data_models.category"),
        ),
        migrations.RemoveField(
            model_name="product",
            name="sub_category",
        ),
        migrations.AddField(
            model_name="product",
            name="sub_category",
            field=models.ManyToManyField(to="data_models.subcategory"),
        ),
    ]
