# Generated by Django 5.1 on 2024-09-28 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_models", "0004_product_category_remove_product_sub_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="vendor_id",
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="vendor_id",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
