# Generated by Django 5.1 on 2024-09-30 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_models", "0005_alter_product_vendor_id_alter_subcategory_vendor_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="ingredients_text",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
